// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe1JApUIJJ9HO0cMgauKig1IrrmRNrStc',
    appId: '1:382098510289:web:a10e2cf12c75c2253610f0',
    messagingSenderId: '382098510289',
    projectId: 'chbaly-adil-master-ai',
    authDomain: 'chbaly-adil-master-ai.firebaseapp.com',
    storageBucket: 'chbaly-adil-master-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_af9gal4KrRiiuUmnSM-ZH9xah6RY04U',
    appId: '1:382098510289:android:bb433761daaa2bb83610f0',
    messagingSenderId: '382098510289',
    projectId: 'chbaly-adil-master-ai',
    storageBucket: 'chbaly-adil-master-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgEO5B9BBx5ZvZnunvBOwXVJCGP5pHZMo',
    appId: '1:382098510289:ios:b92987ccbc47af743610f0',
    messagingSenderId: '382098510289',
    projectId: 'chbaly-adil-master-ai',
    storageBucket: 'chbaly-adil-master-ai.appspot.com',
    iosClientId: '382098510289-4p9uspq4tmor3ha9o61562uvkeu6q8no.apps.googleusercontent.com',
    iosBundleId: 'com.example.recognizemeIa',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgEO5B9BBx5ZvZnunvBOwXVJCGP5pHZMo',
    appId: '1:382098510289:ios:99d4b1f567d596733610f0',
    messagingSenderId: '382098510289',
    projectId: 'chbaly-adil-master-ai',
    storageBucket: 'chbaly-adil-master-ai.appspot.com',
    iosClientId: '382098510289-njhelghv91a6nv37dku0ntec5ocp3lls.apps.googleusercontent.com',
    iosBundleId: 'com.example.recognizemeIa.RunnerTests',
);
}
